z = Board(15)
evergreen = Ship('evergreen', [(0, 0), (0,1), (1, 1), (1, 2)])
bruh = Ship('bruh', [(0, 0), (0,1), (1, 1), (1, 2)])
evergreen.rotate(0)
#bruh.print()
# z.add_ship([evergreen.name, evergreen.shape], (7, 1)) # fuckin rework this entire bit. it should pass in the ship class.
z.add_ship(bruh, (7, 9))
z.add_ship(evergreen, (7, 1))
#z.attempt_move((7, 1))
evergreen.print()
z.attempt_move((7, 2))
#evergreen.print()
z.attempt_move((8, 2))
#evergreen.print()
z.attempt_move((11, 3))
z.print()